"""Recover QTI element names from xsdata's generated models.

This is the module that makes the rest of pyqti possible, and it exists because of
one property of the generated code: **you cannot dispatch on the Python class.**

QTI's expression operators are anonymous types in the XSD, so xsdata regenerated
each one as a ``pass``-body nested subclass once per containing class.
``qti-match`` alone is ``ResponseIfDtype.QtiMatch``, ``SetValueDtype.QtiMatch``,
``LogicPairDtype.QtiMatch`` and a module-level ``any_ndtype.QtiMatch`` --- four
distinct classes for one element, and the pattern repeats across seven modules.

What *is* stable is the QTI element name, and xsdata keeps it in the parent field's
metadata. :func:`iter_children` recovers it, so everything downstream can dispatch
on strings like ``"qti-match"``.

Name recovery has three sources, and the order matters:

1. **The field's own choice metadata** (``var.elements``): a reverse
   ``{type: local_name}`` map. This covers both compound ``Elements`` fields
   (generated by ``--compound-fields``) and mixed wildcard fields --- xsdata
   populates ``var.elements`` for both, e.g. 96 entries for ``Div.content``.
2. **Plain single-type element fields** (``var.is_element``): ``var.local_name``.
3. **The child's own** ``target_qname``, as a last resort.

Source 3 must come last. Leaf HTML classes carry real element qnames
(``P.target_qname`` is ``{qti-ns}p``), but a type like ``SimpleChoiceDtype`` has a
``target_qname`` of ``{qti-ns}SimpleChoiceDType`` --- the *type* name, not an element
name --- so relying on it first would produce nonsense tags.

Preferring metadata over ``type(x).__name__`` is not fastidiousness: it is the only
way to distinguish shared types. ``EmptyPrimitiveTypeDtype`` means ``qti-null`` in
an expression field and ``qti-exit-response`` in ``ResponseProcessingDtype.choice``.
"""

from __future__ import annotations

from collections.abc import Iterator
from functools import cache
from typing import Any

from xsdata.formats.dataclass.models.elements import XmlMeta, XmlVar
from xsdata.formats.dataclass.models.generics import DerivedElement
from xsdata.utils.namespaces import split_qname

from pyqti._xsdata import CONTEXT
from pyqti.errors import QtiStructureError


def local_name(qname: str) -> str:
    """Reduce ``{namespace}tag`` to ``tag``."""
    return split_qname(qname)[1]


def meta_for(cls: type) -> XmlMeta:
    """Return xsdata's metadata for a generated model class."""
    return CONTEXT.build(cls)


@cache
def choice_names(cls: type, field_name: str) -> dict[type, str]:
    """Map each permitted child type of a compound field to its element name.

    xsdata generates the per-parent nested subclasses precisely so that this map is
    injective within a single field --- that property is the load-bearing assumption
    of the whole response-processing compiler, and ``tests/test_qtitree.py`` pins it.
    """
    for var in meta_for(cls).get_all_vars():
        if var.name == field_name and var.is_elements:
            return _reverse_map(var)
    raise QtiStructureError(f"{cls.__name__} has no compound field {field_name!r}")


def _reverse_map(var: XmlVar) -> dict[type, str]:
    mapping: dict[type, str] = {}
    for qname, child_var in var.elements.items():
        name = local_name(qname)
        for tp in child_var.types:
            mapping.setdefault(tp, name)
    return mapping


def choice_name_collisions(cls: type, field_name: str) -> dict[type, set[str]]:
    """Return any child type of a compound field that maps to more than one name.

    Should always be empty. If a model regeneration ever makes it non-empty, name
    recovery becomes ambiguous and the compiler can no longer be trusted, so this
    is asserted in the test suite rather than merely documented.
    """
    for var in meta_for(cls).get_all_vars():
        if var.name == field_name and var.is_elements:
            seen: dict[type, set[str]] = {}
            for qname, child_var in var.elements.items():
                for tp in child_var.types:
                    seen.setdefault(tp, set()).add(local_name(qname))
            return {tp: names for tp, names in seen.items() if len(names) > 1}
    raise QtiStructureError(f"{cls.__name__} has no compound field {field_name!r}")


def _name_from_target_qname(child: Any) -> str | None:
    try:
        target = meta_for(type(child)).target_qname
    except Exception:  # pragma: no cover - non-model values
        return None
    if not target:
        return None
    name = local_name(target)
    # A ``*DType`` target_qname is xsdata reporting the complexType name because the
    # class is not itself a global element. That is not an element name.
    return None if name.endswith("DType") else name


def _resolve_name(child: Any, reverse: dict[type, str], fallback: str | None) -> str:
    if isinstance(child, DerivedElement):
        return local_name(child.qname)

    child_type = type(child)
    if child_type in reverse:
        return reverse[child_type]

    # Subclass of a declared choice (rare, but cheap to tolerate).
    for base in child_type.__mro__[1:]:
        if base in reverse:
            return reverse[base]

    name = _name_from_target_qname(child)
    if name is not None:
        return name
    if fallback is not None:
        return fallback

    raise QtiStructureError(
        f"cannot recover a QTI element name for {child_type.__name__}"
    )


def _unwrap(child: Any) -> Any:
    return child.value if isinstance(child, DerivedElement) else child


def _is_child_var(var: XmlVar) -> bool:
    return bool(var.is_element or var.is_elements or var.is_wildcard)


def _iter_var(
    obj: Any, var: XmlVar, *, include_text: bool
) -> Iterator[tuple[str | None, Any]]:
    value = getattr(obj, var.name, None)
    if value is None:
        return

    # ``var.elements`` is populated for compound (``Elements``) fields *and* for mixed
    # wildcard fields --- ``Div.content`` carries 96 entries --- so both get a reverse
    # map. Only plain single-type element fields fall back to ``var.local_name``.
    reverse = _reverse_map(var) if var.elements else {}
    fallback = var.local_name if var.is_element else None

    for child in value if isinstance(value, list) else [value]:
        if isinstance(child, str):
            if include_text:
                yield None, child
            continue
        yield _resolve_name(child, reverse, fallback), _unwrap(child)


def iter_children(obj: Any) -> Iterator[tuple[str, Any]]:
    """Yield ``(qti_element_local_name, child)`` for a generated model instance.

    Children arrive in field order, which is document order for the compound fields
    this is used on. Text runs inside mixed content are skipped --- use
    :func:`iter_content` when text matters.

    Attributes are not children and are read directly off the dataclass.
    """
    for var in meta_for(type(obj)).get_all_vars():
        if not _is_child_var(var):
            continue
        for name, child in _iter_var(obj, var, include_text=False):
            assert name is not None  # include_text=False never yields None
            yield name, child


def iter_content(obj: Any) -> Iterator[tuple[str | None, Any]]:
    """Like :func:`iter_children`, but yields ``(None, text)`` for text runs.

    Only needed where mixed content matters and the xsdata event stream is not
    already doing the work.
    """
    for var in meta_for(type(obj)).get_all_vars():
        if not _is_child_var(var):
            continue
        yield from _iter_var(obj, var, include_text=True)


def iter_field(obj: Any, field_name: str) -> Iterator[tuple[str, Any]]:
    """Yield ``(element_name, child)`` for **one named field** of a model instance.

    Needed because several QTI containers put semantically different children in
    different fields of the same object. ``ResponseIfDtype.choice`` is the boolean
    condition while ``ResponseIfDtype.choice_1`` is the list of nested rules, so
    :func:`iter_children` --- which merges every field --- cannot tell them apart.
    """
    for var in meta_for(type(obj)).get_all_vars():
        if var.name != field_name:
            continue
        if not _is_child_var(var):
            raise QtiStructureError(
                f"{type(obj).__name__}.{field_name} is not an element field"
            )
        for name, child in _iter_var(obj, var, include_text=False):
            assert name is not None
            yield name, child
        return

    raise QtiStructureError(f"{type(obj).__name__} has no field {field_name!r}")


def first_child(obj: Any, name: str) -> Any | None:
    """Return the first child of ``obj`` named ``name``, or ``None``."""
    for child_name, child in iter_children(obj):
        if child_name == name:
            return child
    return None


def children_named(obj: Any, name: str) -> list[Any]:
    """Return every child of ``obj`` named ``name``."""
    return [child for child_name, child in iter_children(obj) if child_name == name]
