from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "http://www.imsglobal.org/xsd/imsqtiasi_v3p0"


class AriabaseDtypeRole(Enum):
    """
    The permitted set of values for the ARIA roles that have been
    identified as applicable to QTI XML markup.
    """

    ARTICLE = "article"
    COLUMNHEADER = "columnheader"
    DEFINITION = "definition"
    DOCUMENT = "document"
    GROUP = "group"
    HEADING = "heading"
    IMG = "img"
    LIST = "list"
    LISTITEM = "listitem"
    MATH = "math"
    NOTE = "note"
    PRESENTATION = "presentation"
    REGION = "region"
    ROW = "row"
    ROWGROUP = "rowgroup"
    ROWHEADER = "rowheader"
    SEPARATOR = "separator"
    TOOLBAR = "toolbar"
    BUTTON = "button"
    CHECKBOX = "checkbox"
    GRIDCELL = "gridcell"
    LINK = "link"
    LOG = "log"
    OPTION = "option"
    RADIO = "radio"
    SLIDER = "slider"
    SPINBUTTON = "spinbutton"
    STATUS = "status"
    TAB = "tab"
    TABPANEL = "tabpanel"
    TEXTBOX = "textbox"
    TIMER = "timer"
    LISTBOX = "listbox"
    RADIOGROUP = "radiogroup"
    TABLIST = "tablist"
    COMPLEMENTARY = "complementary"
    CONTENTINFO = "contentinfo"
    ALERT = "alert"
    ALERTDIALOG = "alertdialog"
    APPLICATION = "application"
    BANNER = "banner"
    COMBOBOX = "combobox"
    DIALOG = "dialog"
    FORM = "form"
    GRID = "grid"
    MAIN = "main"
    MARQUEE = "marquee"
    MENU = "menu"
    MENUBAR = "menubar"
    MENUITEM = "menuitem"
    MENUITEMCHECKBOX = "menuitemcheckbox"
    MENUITEMRADIO = "menuitemradio"
    NAVIGATION = "navigation"
    PROGRESSBAR = "progressbar"
    SCROLLBAR = "scrollbar"
    SEARCH = "search"
    TOOLTIP = "tooltip"
    TREE = "tree"
    TREEGRID = "treegrid"
    TREEITEM = "treeitem"
    SEARCHBOX = "searchbox"
    SWITCH = "switch"
    TERM = "term"
    FIGURE = "figure"
    CODE = "code"
    TIME = "time"
    SUBSCRIPT = "subscript"
    SUPERSCRIPT = "superscript"
    METER = "meter"
    GENERIC = "generic"
    INSERTION = "insertion"
    DELETION = "deletion"
    STRONG = "strong"
    EMPHASIS = "emphasis"
